insert into device (part_number, description) values ('01-100-00', 'Managed: A-Backup Server Management');
insert into device (part_number, description) values ('01-100-01', 'Managed: B-Disk Staging Area');
insert into device (part_number, description) values ('01-100-02', 'Managed: C-Backup Agents / API (per group of 5)');
insert into device (part_number, description) values ('01-100-03', 'Managed: C-Backup Local Clients or VM Snapshots (per group of 20)');
insert into device (part_number, description) values ('01-100-04', 'Managed: M-Media Rotation Assistance - Open Media Registration (per 15 tapes)');
insert into device (part_number, description) values ('01-100-05', 'Managed: Z-NetBackup Deduplication Licensing (Product-Bronze ONLY)');
insert into device (part_number, description) values ('01-100-06', 'Managed: Z-NetBackup Platform Licensing (Product-Bronze ONLY)');
insert into device (part_number, description) values ('01-101-00', 'Managed: A-Media Server');
insert into device (part_number, description) values ('01-102-00', 'Managed: B-Library Management (per 12 drives)');
insert into device (part_number, description) values ('01-300-01', 'Virtual/Hosted: A-Per GB DB/Application Backup Capacity');
insert into device (part_number, description) values ('01-300-02', 'Virtual/Hosted: A-Per GB OS (Files) Backup Capacity');
insert into device (part_number, description) values ('01-300-03', 'Virtual/Hosted: C-Backup Agents / API (per group of 5)');
insert into device (part_number, description) values ('01-300-04', 'Virtual/Hosted: C-Management of Backup Clients or VM Snapshots (per group of 20)');
insert into device (part_number, description) values ('01-300-05', 'Virtual/Hosted: EOM Tape - 7 yr Offsite Storage (per Tape)');
insert into device (part_number, description) values ('01-300-06', 'Virtual/Hosted: L-NetBackup DB and Application Pack - Tier 2 (License Only)');
insert into device (part_number, description) values ('01-300-07', 'Virtual/Hosted: L-NetBackup Enterprise Client - Tier 2 (License only)');
insert into device (part_number, description) values ('01-300-08', 'Virtual/Hosted: L-NetBackup Standard Client - (License Only)');
insert into device (part_number, description) values ('01-300-09', 'Virtual/Hosted: Offsite Vaulting - Per GB');
insert into device (part_number, description) values ('02-100-00', '1/4 Rack with power');
insert into device (part_number, description) values ('03-100-00', 'Oracle 10g,  Per instance');
insert into device (part_number, description) values ('03-101-00', 'Oracle 10g, RAC, Per instance in cluster');
insert into device (part_number, description) values ('03-110-00', 'Oracle 11g, Per instance');
insert into device (part_number, description) values ('03-111-00', 'Oracle 11g, RAC, Per instance in cluster');
insert into device (part_number, description) values ('03-200-00', 'SQL Server, Per instance');
insert into device (part_number, description) values ('04-100-01', 'Managed Services Only: SS (Self-Service)');
insert into device (part_number, description) values ('04-100-02', 'Managed Services Only: SSP (Self-Service Plus)');
insert into device (part_number, description) values ('04-300-01', 'Help Desk Express: H-ITSM (ITSM w/Help Desk Express)');
insert into device (part_number, description) values ('04-300-02', 'Help Desk Express: H-SS (Self-Service w/Help Desk Express)');
insert into device (part_number, description) values ('04-300-03', 'Help Desk Express: H-SSP (Self-Service Plus w/Help Desk Express)');
insert into device (part_number, description) values ('04-401-00', 'First Point of Contact: 250-300 Incidents/month');
insert into device (part_number, description) values ('04-402-00', 'First Point of Contact: 301-400 Incidents/month');
insert into device (part_number, description) values ('04-403-00', 'First Point of Contact: 401-500 Incidents/month');
insert into device (part_number, description) values ('04-404-00', 'First Point of Contact: 501-600 Incidents/month');
insert into device (part_number, description) values ('04-405-00', 'First Point of Contact: 601-700 Incidents/month');
insert into device (part_number, description) values ('04-406-00', 'First Point of Contact: 701-800 Incidents/month');
insert into device (part_number, description) values ('04-407-00', 'First Point of Contact: 801-900 Incidents/month');
insert into device (part_number, description) values ('04-408-00', 'First Point of Contact: 901-999 Incidents/month');
insert into device (part_number, description) values ('05-200-00', 'Container - x86/Linux -  Master (Add options as needed)');
insert into device (part_number, description) values ('05-200-01', 'Container - x86/Linux - Bandwidth (per Megabit/Sec) - Qty  1 to 19');
insert into device (part_number, description) values ('05-200-01', 'Container - x86/Linux - Bandwidth (per Megabit/Sec) - Qty 20 to 39');
insert into device (part_number, description) values ('05-200-01', 'Container - x86/Linux - Bandwidth (per Megabit/Sec) - Qty 40+');
insert into device (part_number, description) values ('05-200-02', 'Container - x86/Linux - CPU (per GHz) - Qty   1 to 39');
insert into device (part_number, description) values ('05-200-02', 'Container - x86/Linux - CPU (per GHz) - Qty  40 to 89');
insert into device (part_number, description) values ('05-200-02', 'Container - x86/Linux - CPU (per GHz) - Qty  90 to 149');
insert into device (part_number, description) values ('05-200-02', 'Container - x86/Linux - CPU (per GHz) - Qty 150+');
insert into device (part_number, description) values ('05-200-03', 'Container - x86/Linux - Memory (per GB) - Qty   1 to 79');
insert into device (part_number, description) values ('05-200-03', 'Container - x86/Linux - Memory (per GB) - Qty  80 to 149');
insert into device (part_number, description) values ('05-200-03', 'Container - x86/Linux - Memory (per GB) - Qty 150 to 224');
insert into device (part_number, description) values ('05-200-03', 'Container - x86/Linux - Memory (per GB) - Qty 225+');
insert into device (part_number, description) values ('05-200-04', 'Container - x86/Linux - Setup Fee');
insert into device (part_number, description) values ('05-200-05', 'Container - x86/Linux - Storage (per GB) - Qty     1 to 4999');
insert into device (part_number, description) values ('05-200-05', 'Container - x86/Linux - Storage (per GB) - Qty  5000 to 9999');
insert into device (part_number, description) values ('05-200-05', 'Container - x86/Linux - Storage (per GB) - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-200-05', 'Container - x86/Linux - Storage (per GB) - Qty 20000+');
insert into device (part_number, description) values ('05-200-06', 'Container - x86/Linux - Storage, Encrypted (per GB) - Qty     1 to 4999');
insert into device (part_number, description) values ('05-200-06', 'Container - x86/Linux - Storage, Encrypted (per GB) - Qty  5000 to 9999');
insert into device (part_number, description) values ('05-200-06', 'Container - x86/Linux - Storage, Encrypted (per GB) - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-200-06', 'Container - x86/Linux - Storage, Encrypted (per GB) - Qty 20000+');
insert into device (part_number, description) values ('05-200-07', 'Container - x86/Linux - External IP Addresses (each)');
insert into device (part_number, description) values ('05-210-00', 'Container - DR x86/Linux -  Master (Add options as needed)');
insert into device (part_number, description) values ('05-210-01', 'Container - DR x86/Linux - Bandwidth (per Megabit/Sec) - Qty  1 to 19');
insert into device (part_number, description) values ('05-210-01', 'Container - DR x86/Linux - Bandwidth (per Megabit/Sec) - Qty 20 to 39');
insert into device (part_number, description) values ('05-210-01', 'Container - DR x86/Linux - Bandwidth (per Megabit/Sec) - Qty 40+');
insert into device (part_number, description) values ('05-210-02', 'Container - DR x86/Linux - CPU (per GHz) - Qty  1 to 39');
insert into device (part_number, description) values ('05-210-02', 'Container - DR x86/Linux - CPU (per GHz) - Qty  40 to 89');
insert into device (part_number, description) values ('05-210-02', 'Container - DR x86/Linux - CPU (per GHz) - Qty  90 to 149');
insert into device (part_number, description) values ('05-210-02', 'Container - DR x86/Linux - CPU (per GHz) - Qty 150+');
insert into device (part_number, description) values ('05-210-03', 'Container - DR x86/Linux - Memory (per GB) - Qty  1 to 79');
insert into device (part_number, description) values ('05-210-03', 'Container - DR x86/Linux - Memory (per GB) - Qty  80 to 149');
insert into device (part_number, description) values ('05-210-03', 'Container - DR x86/Linux - Memory (per GB) - Qty 150+');
insert into device (part_number, description) values ('05-210-04', 'Container - DR x86/Linux - Storage (per GB) - Qty   1 to 4999');
insert into device (part_number, description) values ('05-210-04', 'Container - DR x86/Linux - Storage (per GB) - Qty  5000 to 9999');
insert into device (part_number, description) values ('05-210-04', 'Container - DR x86/Linux - Storage (per GB) - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-210-04', 'Container - DR x86/Linux - Storage (per GB) - Qty 20000+');
insert into device (part_number, description) values ('05-210-05', 'Container - DR x86/Linux - Storage, Encrypted (per GB) - Qty     1 to 4999');
insert into device (part_number, description) values ('05-210-05', 'Container - DR x86/Linux - Storage, Encrypted (per GB) - Qty  5000 to 9999');
insert into device (part_number, description) values ('05-210-05', 'Container - DR x86/Linux - Storage, Encrypted (per GB) - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-210-05', 'Container - DR x86/Linux - Storage, Encrypted (per GB) - Qty 20000+');
insert into device (part_number, description) values ('05-210-06', 'Container - DR x86/Linux - Setup Fee');
insert into device (part_number, description) values ('05-210-07', 'Container - DR x86/Linux - External IP Addresses (each)');
insert into device (part_number, description) values ('05-220-00', 'Container - POWER -  Master (Add options as needed)');
insert into device (part_number, description) values ('05-220-01', 'Container - POWER - Bandwidth (per Megabit/Sec) - Qty  1 to 19');
insert into device (part_number, description) values ('05-220-01', 'Container - POWER - Bandwidth (per Megabit/Sec) - Qty 20 to 49');
insert into device (part_number, description) values ('05-220-01', 'Container - POWER - Bandwidth (per Megabit/Sec) - Qty 50+');
insert into device (part_number, description) values ('05-220-02', 'Container - POWER - AIX (rPerf) 5.3, 6.1, & 7.1 - Qty  1 to 59');
insert into device (part_number, description) values ('05-220-02', 'Container - POWER - AIX (rPerf) 5.3, 6.1, & 7.1 - Qty  60 to 109');
insert into device (part_number, description) values ('05-220-02', 'Container - POWER - AIX (rPerf) 5.3, 6.1, & 7.1 - Qty 110 to 159');
insert into device (part_number, description) values ('05-220-02', 'Container - POWER - AIX (rPerf) 5.3, 6.1, & 7.1 - Qty 160+');
insert into device (part_number, description) values ('05-220-03', 'Container - POWER - i5os (CPW) V6R1 & V7R1 - Qty    1 to 9999');
insert into device (part_number, description) values ('05-220-03', 'Container - POWER - i5os (CPW) V6R1 & V7R1 - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-220-03', 'Container - POWER - i5os (CPW) V6R1 & V7R1 - Qty 20000 to 39999');
insert into device (part_number, description) values ('05-220-03', 'Container - POWER - i5os (CPW) V6R1 & V7R1 - Qty 40000+');
insert into device (part_number, description) values ('05-220-04', 'Container - POWER - Memory (per GB) - Qty   1 to 74');
insert into device (part_number, description) values ('05-220-04', 'Container - POWER - Memory (per GB) - Qty  75 to 149');
insert into device (part_number, description) values ('05-220-04', 'Container - POWER - Memory (per GB) - Qty 150 to 249');
insert into device (part_number, description) values ('05-220-04', 'Container - POWER - Memory (per GB) - Qty 250+');
insert into device (part_number, description) values ('05-220-05', 'Container - POWER - Storage (per GB) - Qty   1 to 4999');
insert into device (part_number, description) values ('05-220-05', 'Container - POWER - Storage (per GB) - Qty  5000 to 9999');
insert into device (part_number, description) values ('05-220-05', 'Container - POWER - Storage (per GB) - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-220-05', 'Container - POWER - Storage (per GB) - Qty 20000+');
insert into device (part_number, description) values ('05-220-06', 'Container - POWER - Storage, Encrypted (per GB) - Qty    1 to 4999');
insert into device (part_number, description) values ('05-220-06', 'Container - POWER - Storage, Encrypted (per GB) - Qty  5000 to 9999');
insert into device (part_number, description) values ('05-220-06', 'Container - POWER - Storage, Encrypted (per GB) - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-220-06', 'Container - POWER - Storage, Encrypted (per GB) - Qty 20000+');
insert into device (part_number, description) values ('05-220-07', 'Container - POWER - Setup Fee');
insert into device (part_number, description) values ('05-220-08', 'Container - POWER - External IP Addresses (each)');
insert into device (part_number, description) values ('05-230-00', 'Container - DR POWER -  Master (Add options as needed)');
insert into device (part_number, description) values ('05-230-01', 'Container - DR POWER - Bandwidth (per Megabit/Sec) - Qty  1 to 19');
insert into device (part_number, description) values ('05-230-01', 'Container - DR POWER - Bandwidth (per Megabit/Sec) - Qty 20 to 49');
insert into device (part_number, description) values ('05-230-01', 'Container - DR POWER - Bandwidth (per Megabit/Sec) - Qty 50+');
insert into device (part_number, description) values ('05-230-02', 'Container - DR POWER - AIX (rPerf) 5.3, 6.1, 7.1 - Qty  1 to 59');
insert into device (part_number, description) values ('05-230-02', 'Container - DR POWER - AIX (rPerf) 5.3, 6.1, 7.1 - Qty  60 to 109');
insert into device (part_number, description) values ('05-230-02', 'Container - DR POWER - AIX (rPerf) 5.3, 6.1, 7.1 - Qty 110 - 159');
insert into device (part_number, description) values ('05-230-02', 'Container - DR POWER - AIX (rPerf) 5.3, 6.1, 7.1 - Qty 160 +');
insert into device (part_number, description) values ('05-230-03', 'Container - DR POWER - i5os (CPW) V6R1 & V7R1 - Qty    1 to 9999');
insert into device (part_number, description) values ('05-230-03', 'Container - DR POWER - i5os (CPW) V6R1 & V7R1 - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-230-03', 'Container - DR POWER - i5os (CPW) V6R1 & V7R1 - Qty 20000 to 39999');
insert into device (part_number, description) values ('05-230-03', 'Container - DR POWER - i5os (CPW) V6R1 & V7R1 - Qty 40000+');
insert into device (part_number, description) values ('05-230-04', 'Container - DR POWER - Memory (per GB) - Qty   1 to 74');
insert into device (part_number, description) values ('05-230-04', 'Container - DR POWER - Memory (per GB) - Qty  75 to 149');
insert into device (part_number, description) values ('05-230-04', 'Container - DR POWER - Memory (per GB) - Qty 150 to 249');
insert into device (part_number, description) values ('05-230-04', 'Container - DR POWER - Memory (per GB) - Qty 250+');
insert into device (part_number, description) values ('05-230-05', 'Container - DR POWER - Storage (per GB) - Qty   1 to 4999');
insert into device (part_number, description) values ('05-230-05', 'Container - DR POWER - Storage (per GB) - Qty  5000 to 9999');
insert into device (part_number, description) values ('05-230-05', 'Container - DR POWER - Storage (per GB) - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-230-05', 'Container - DR POWER - Storage (per GB) - Qty 20000+');
insert into device (part_number, description) values ('05-230-06', 'Container - DR POWER - Storage, Encrypted (per GB) - Qty    1 to 4999');
insert into device (part_number, description) values ('05-230-06', 'Container - DR POWER - Storage, Encrypted (per GB) - Qty  5000 to 9999');
insert into device (part_number, description) values ('05-230-06', 'Container - DR POWER - Storage, Encrypted (per GB) - Qty 10000 to 19999');
insert into device (part_number, description) values ('05-230-06', 'Container - DR POWER - Storage, Encrypted (per GB) - Qty 20000+');
insert into device (part_number, description) values ('05-230-08', 'Container - DR POWER - External IP Addresses (each)');
insert into device (part_number, description) values ('05-230-10', 'Container - DR POWER - Setup Fee');
insert into device (part_number, description) values ('05-300-00', 'Server - Windows or Linux - 1 VCPU');
insert into device (part_number, description) values ('05-301-00', 'Server - Windows or Linux - 2 VCPU');
insert into device (part_number, description) values ('05-302-00', 'Server - Windows or Linux - 4 VCPU');
insert into device (part_number, description) values ('05-303-00', 'Server - Windows or Linux - 8 VCPU');
insert into device (part_number, description) values ('05-350-00', 'Server - AIX');
insert into device (part_number, description) values ('05-360-00', 'Server - i5os');
insert into device (part_number, description) values ('05-400-00', 'Software - Citrix XenApp');
insert into device (part_number, description) values ('05-409-00', 'Software - Microsoft Office Suite, Office Pro Plus Edition (Per User)');
insert into device (part_number, description) values ('05-410-00', 'Software - Microsoft Office Suite, Standard Edition (Per User)');
insert into device (part_number, description) values ('05-413-00', 'Software - Microsoft Sharepoint, Enterprise (Per User)');
insert into device (part_number, description) values ('05-414-00', 'Software - Microsoft Sharepoint, Standard (Per User)');
insert into device (part_number, description) values ('05-420-00', 'Software - Microsoft Visio - Visio Premium');
insert into device (part_number, description) values ('05-421-00', 'Software - Microsoft Visio - Visio Pro');
insert into device (part_number, description) values ('05-422-00', 'Software - Microsoft Visio - Visio Standard');
insert into device (part_number, description) values ('05-430-00', 'Software - MS SQL - Enterprise Edition, Per User');
insert into device (part_number, description) values ('05-431-00', 'Software - MS SQL - Enterprise Edition, Unlimited users - 2 VCPU ');
insert into device (part_number, description) values ('05-432-00', 'Software - MS SQL - Enterprise Edition, Unlimited users - 4 VCPU ');
insert into device (part_number, description) values ('05-433-00', 'Software - MS SQL - Enterprise Edition, Unlimited users - 8 VCPU ');
insert into device (part_number, description) values ('05-440-00', 'Software - MS SQL - Standard Edition, Per User');
insert into device (part_number, description) values ('05-441-00', 'Software - MS SQL - Standard Edition, Unlimited users - 1 VCPU ');
insert into device (part_number, description) values ('05-442-00', 'Software - MS SQL - Standard Edition, Unlimited users - 2 VCPU ');
insert into device (part_number, description) values ('05-443-00', 'Software - MS SQL - Standard Edition, Unlimited users - 4 VCPU ');
insert into device (part_number, description) values ('05-444-00', 'Software - MS SQL - Standard Edition, Unlimited users - 8 VCPU ');
insert into device (part_number, description) values ('05-450-00', 'Software - MS SQL - Web Edition, Unlimited users - 1 VCPU ');
insert into device (part_number, description) values ('05-451-00', 'Software - MS SQL - Web Edition, Unlimited users - 2 VCPU ');
insert into device (part_number, description) values ('05-452-00', 'Software - MS SQL - Web Edition, Unlimited users - 4 VCPU ');
insert into device (part_number, description) values ('05-500-00', 'Load Balancer - Small');
insert into device (part_number, description) values ('05-501-00', 'Load Balancer - Medium');
insert into device (part_number, description) values ('05-502-00', 'Load Balancer - Large');
insert into device (part_number, description) values ('05-510-00', 'Vyatta Network Appliance');
insert into device (part_number, description) values ('05-601-00', 'Networking - Cross Connect Fee');
insert into device (part_number, description) values ('05-602-00', 'Networking - Port Connection Fee');
insert into device (part_number, description) values ('05-603-00', 'WAN Accelerator - Cloud Steelhead  250-H ( 6 month)');
insert into device (part_number, description) values ('05-604-00', 'WAN Accelerator - Cloud Steelhead  250-H (12 month)');
insert into device (part_number, description) values ('05-605-00', 'WAN Accelerator - Cloud Steelhead  250-H (36 month)');
insert into device (part_number, description) values ('05-606-00', 'WAN Accelerator - Cloud Steelhead  550-H ( 6 month)');
insert into device (part_number, description) values ('05-607-00', 'WAN Accelerator - Cloud Steelhead  550-H (12 month)');
insert into device (part_number, description) values ('05-608-00', 'WAN Accelerator - Cloud Steelhead  550-H (36 month)');
insert into device (part_number, description) values ('05-609-00', 'WAN Accelerator - Cloud Steelhead 1050-H ( 6 month)');
insert into device (part_number, description) values ('05-610-00', 'WAN Accelerator - Cloud Steelhead 1050-H (12 month)');
insert into device (part_number, description) values ('05-611-00', 'WAN Accelerator - Cloud Steelhead 1050-H (36 month)');
insert into device (part_number, description) values ('05-612-00', 'WAN Accelerator - Cloud Steelhead 1050-M ( 6 month)');
insert into device (part_number, description) values ('05-613-00', 'WAN Accelerator - Cloud Steelhead 1050-M (12 month)');
insert into device (part_number, description) values ('05-614-00', 'WAN Accelerator - Cloud Steelhead 1050-M (36 month)');
insert into device (part_number, description) values ('05-615-00', 'WAN Accelerator - Cloud Steelhead 2050-L ( 6 month)');
insert into device (part_number, description) values ('05-616-00', 'WAN Accelerator - Cloud Steelhead 2050-L (12 month)');
insert into device (part_number, description) values ('05-617-00', 'WAN Accelerator - Cloud Steelhead 2050-L (36 month)');
insert into device (part_number, description) values ('06-100-01', 'Exchange Server/App -  Includes first 100 Mailboxes');
insert into device (part_number, description) values ('06-100-02', 'Exchange Server/App - Add:  100 Mailboxes');
insert into device (part_number, description) values ('06-100-03', 'Exchange Server/App - Add: OWA login testing');
insert into device (part_number, description) values ('06-100-04', 'Exchange Server/App - Add: End-to-end testing');
insert into device (part_number, description) values ('06-200-01', 'SaaS E-Mail and Web Security: E-Mail Inbound Filtering');
insert into device (part_number, description) values ('06-200-02', 'SaaS E-Mail and Web Security: E-Mail Protection (In/Out Filtering)');
insert into device (part_number, description) values ('06-200-03', 'SaaS E-Mail and Web Security: E-Mail Protection and Continuity');
insert into device (part_number, description) values ('06-200-04', 'SaaS E-Mail and Web Security: Web Total Control (Threat and Content)');
insert into device (part_number, description) values ('06-210-01', 'SaaS E-Mail and Web Security: McAfee E-Mail Archiving 1-Year Retention ( 1-400 copies)');
insert into device (part_number, description) values ('06-210-02', 'SaaS E-Mail and Web Security: McAfee E-Mail Archiving 1-Year Retention (401+ copies)');
insert into device (part_number, description) values ('06-220-01', 'SaaS E-Mail and Web Security: McAfee E-Mail Archiving Multi-Year Retention ( 1-400 copies)');
insert into device (part_number, description) values ('06-220-02', 'SaaS E-Mail and Web Security: McAfee E-Mail Archiving Multi-Year Retention (401+ copies)');
insert into device (part_number, description) values ('06-230-01', 'SaaS E-Mail and Web Security: McAfee E-Mail Encryption (   1-100 copies)');
insert into device (part_number, description) values ('06-230-02', 'SaaS E-Mail and Web Security: McAfee E-Mail Encryption ( 101-400 copies)');
insert into device (part_number, description) values ('06-230-03', 'SaaS E-Mail and Web Security: McAfee E-Mail Encryption ( 401-1000 copies)');
insert into device (part_number, description) values ('06-230-04', 'SaaS E-Mail and Web Security: McAfee E-Mail Encryption (1001-2000 copies)');
insert into device (part_number, description) values ('06-230-05', 'SaaS E-Mail and Web Security: McAfee E-Mail Encryption (2000+ copies)');
insert into device (part_number, description) values ('07-100-00', 'Complex Network Device');
insert into device (part_number, description) values ('07-200-00', 'Firewall / VPN Appliance - Cisco');
insert into device (part_number, description) values ('07-210-00', 'Firewall, Small - Juniper');
insert into device (part_number, description) values ('07-211-00', 'Firewall, Large - Juniper');
insert into device (part_number, description) values ('07-300-00', 'Router, Large - Cisco, Juniper and H3C devices');
insert into device (part_number, description) values ('07-301-00', 'Router, Large - Other devices');
insert into device (part_number, description) values ('07-302-00', 'Router, Small - Cisco, Juniper and H3C devices');
insert into device (part_number, description) values ('07-303-00', 'Router, Small - Other devices');
insert into device (part_number, description) values ('07-400-00', 'Switch, Large - Cisco, Juniper and HP devices');
insert into device (part_number, description) values ('07-401-00', 'Switch, Large - Other devices');
insert into device (part_number, description) values ('07-402-00', 'Switch, Small - Cisco, Juniper and HP devices');
insert into device (part_number, description) values ('07-403-00', 'Switch, Small - Other devices');
insert into device (part_number, description) values ('07-500-00', 'WAN Acceleration Appliance');
insert into device (part_number, description) values ('07-600-00', 'LAP, Monitored (Only if WLC is monitored or managed also)');
insert into device (part_number, description) values ('07-700-00', 'WAP, Managed');
insert into device (part_number, description) values ('07-701-00', 'WAP, Monitored (Only if WLC is monitored or managed also)');
insert into device (part_number, description) values ('07-800-00', 'Riverbed Steelhead');
insert into device (part_number, description) values ('08-100-00', 'Blade Chassis');
insert into device (part_number, description) values ('08-200-00', 'Citrix XenApp Management - Per Server');
insert into device (part_number, description) values ('08-210-00', 'Citrix Provisioning Server');
insert into device (part_number, description) values ('08-300-00', 'High Availability: MC/ServiceGuard Package');
insert into device (part_number, description) values ('08-310-00', 'High Availability: UNIX Power HA');
insert into device (part_number, description) values ('08-600-00', 'Synthetic Transactions: Level 1 - Websites');
insert into device (part_number, description) values ('08-601-00', 'Synthetic Transactions: Level 2 - Web Applications');
insert into device (part_number, description) values ('08-602-00', 'Synthetic Transactions: Level 3 - Enterprise Applications');
insert into device (part_number, description) values ('08-603-00', 'Synthetic Transactions: Level 0 - Availability testing only');
insert into device (part_number, description) values ('08-700-00', 'Device Up / Down Monitoring');
insert into device (part_number, description) values ('08-701-00', 'ServiceDesk:   0 - 117 incidents/month');
insert into device (part_number, description) values ('08-702-00', 'ServiceDesk:  118 - 200 Incidents/month');
insert into device (part_number, description) values ('08-703-00', 'ServiceDesk:  201 - 300 incidents/month');
insert into device (part_number, description) values ('08-704-00', 'ServiceDesk:  301 - 400 incidents/month');
insert into device (part_number, description) values ('08-705-00', 'ServiceDesk:  401 - 600 incidents/month');
insert into device (part_number, description) values ('08-706-00', 'ServiceDesk:  601 - 750 incidents/month');
insert into device (part_number, description) values ('08-707-00', 'ServiceDesk:  751 - 1000 incidents/month');
insert into device (part_number, description) values ('08-708-00', 'ServiceDesk: 1001 - 1250 incidents/month');
insert into device (part_number, description) values ('08-709-00', 'ServiceDesk: 1251 - 1500 incidents/month');
insert into device (part_number, description) values ('08-750-00', 'ServiceDesk: Toolset one-time fee (optional)');
insert into device (part_number, description) values ('08-760-00', 'ServiceDesk: Level 2 Incident Units (30 min each) - Minimum 10/month');
insert into device (part_number, description) values ('09-100-00', 'Security Device - Type 1');
insert into device (part_number, description) values ('09-200-00', 'Security Device - Type 2');
insert into device (part_number, description) values ('09-300-00', 'Security Device - Type 3');
insert into device (part_number, description) values ('09-400-00', 'Security Device - Type 4');
insert into device (part_number, description) values ('09-500-00', 'Security Device - Type 5');
insert into device (part_number, description) values ('10-100-00', 'AIX');
insert into device (part_number, description) values ('10-200-00', 'Linux');
insert into device (part_number, description) values ('10-300-00', 'System I (iSeries / AS400)');
insert into device (part_number, description) values ('10-400-00', 'Solaris');
insert into device (part_number, description) values ('10-500-00', 'HPUX');
insert into device (part_number, description) values ('10-600-00', 'Windows');
insert into device (part_number, description) values ('10-610-00', 'Windows Blade');
insert into device (part_number, description) values ('11-100-00', 'Storage Array with   1 to 25 TB, 1 or 2 controllers');
insert into device (part_number, description) values ('11-101-00', 'Storage Array with  26 to 75 TB, 4 or fewer controllers');
insert into device (part_number, description) values ('11-102-00', 'Storage Array with  76 to 200 TB, 4 or fewer controllers');
insert into device (part_number, description) values ('11-103-00', 'Storage Array with 201 to 400 TB, 4 or more controllers');
insert into device (part_number, description) values ('11-104-00', 'Storage Array with 401 to 700 TB, 4 or more controllers');
insert into device (part_number, description) values ('11-200-00', 'Storage Array Add-On: Remote Replication (Per 100 TB Replicated)');
insert into device (part_number, description) values ('11-210-00', 'Storage Array Add-On: Storage Virtualization (Per Controller Pair Device Monitoring)');
insert into device (part_number, description) values ('11-220-00', 'Storage Array Add-On: Unified (Block & File)');
insert into device (part_number, description) values ('11-300-00', 'Multi-Protocol Router');
insert into device (part_number, description) values ('11-400-00', 'SAN Switch - Small  (8 to 64 Ports)');
insert into device (part_number, description) values ('11-400-01', 'SAN Switch - Small - Add-On FCIP');
insert into device (part_number, description) values ('11-410-00', 'SAN Switch - Medium  (65 to 256 Ports)');
insert into device (part_number, description) values ('11-410-01', 'SAN Switch - Medium - Add-On FCIP');
insert into device (part_number, description) values ('11-420-00', 'SAN Switch - Large  (257 to 528 Ports)');
insert into device (part_number, description) values ('11-420-01', 'SAN Switch - Large - Add-On FCIP');
insert into device (part_number, description) values ('12-100-00', 'Cisco Unified Communications Manager');
insert into device (part_number, description) values ('12-101-00', 'Cisco Unified Communications Manager (Call Manager Express and Router)');
insert into device (part_number, description) values ('12-150-00', 'Cisco Unified Communications Manager (Business Edition)');
insert into device (part_number, description) values ('12-160-00', 'Cisco Unified Contact Center Express:  Up to 10 agents and 3 queues');
insert into device (part_number, description) values ('12-160-01', 'Cisco Unified Contact Center Express: Opt - Add 1 more queue');
insert into device (part_number, description) values ('12-160-02', 'Cisco Unified Contact Center Express: Opt - Add 5 more agents');
insert into device (part_number, description) values ('12-200-00', 'Cisco IOS Gateway');
insert into device (part_number, description) values ('12-300-00', 'Phone');
insert into device (part_number, description) values ('12-400-00', 'Cisco Unity (Now called \'Cisco Unity Connection\')');
insert into device (part_number, description) values ('12-401-00', 'Cisco Unity Express (CUE)');
insert into device (part_number, description) values ('12-402-00', 'Cisco Unity Server');
insert into device (part_number, description) values ('12-500-00', 'Cisco Unified Presense / Jabber  (Windows server)');
insert into device (part_number, description) values ('12-501-00', 'Sagem Xmedius Fax Server (Windows server)');
insert into device (part_number, description) values ('12-502-00', 'Cisco Unified Attendant Console (CUAC)');
insert into device (part_number, description) values ('13-100-00', 'VMware ESX Host');
insert into device (part_number, description) values ('13-101-00', 'VMware ESX i Host');
insert into device (part_number, description) values ('14-100-00', 'Bronze Plus Hours');
insert into device (part_number, description) values ('14-200-00', 'IP/T - Cisco - Bronze Plus');
insert into device (part_number, description) values ('14-300-00', 'Networking - Cisco - Bronze Plus');
insert into device (part_number, description) values ('14-400-00', 'VMWare - Bronze Plus');
insert into device (part_number, description) values ('14-500-00', 'Windows - Bronze Plus');
insert into device (part_number, description) values ('15-100-00', 'Network Devices -    1 to 20');
insert into device (part_number, description) values ('15-101-00', 'Network Devices -   21 to 50');
insert into device (part_number, description) values ('15-102-00', 'Network Devices -   51 to 100');
insert into device (part_number, description) values ('15-103-00', 'Network Devices -  101 to 250');
insert into device (part_number, description) values ('15-104-00', 'Network Devices -  251 to 500');
insert into device (part_number, description) values ('15-105-00', 'Network Devices -  501 to 1000');
insert into device (part_number, description) values ('15-106-00', 'Network Devices - 1001 to 1500');
insert into device (part_number, description) values ('15-107-00', 'Network Devices - 1501 to 3000');
insert into device (part_number, description) values ('15-200-00', 'Servers -    1 to 20');
insert into device (part_number, description) values ('15-201-00', 'Servers -   21 to 50');
insert into device (part_number, description) values ('15-202-00', 'Servers -   51 to 100');
insert into device (part_number, description) values ('15-203-00', 'Servers -  101 to 250');
insert into device (part_number, description) values ('15-204-00', 'Servers -  251 to 300');
insert into device (part_number, description) values ('15-205-00', 'Servers -  301 to 400');
insert into device (part_number, description) values ('15-206-00', 'Servers -  401 to 500');
insert into device (part_number, description) values ('15-207-00', 'Servers -  501 to 750');
insert into device (part_number, description) values ('15-300-00', 'Nimsoft Hub - On Site Monitoring Server');